### ISSUE TITLE
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by KrishnenduSG** [wit-ai/wit#2094]
Hi, I am getting this error, please tell how to resolve it.....

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Krishnendu\Desktop\Witproject\lib\site-packages\wit\wit.py", line 69, in message
    resp = req(self.logger, self.access_token, 'GET', '/message', params)
  File "C:\Users\Krishnendu\Desktop\Witproject\lib\site-packages\wit\wit.py", line 42, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)
>>>

**Comment by chessai** [comment]
What is your App ID?

**Comment by chessai** [comment]
See https://github.com/wit-ai/wit/issues/2105#issuecomment-856296095

**Comment by chessai** [comment]
This should be resolved. See https://github.com/wit-ai/wit/issues/2105#issuecomment-860916172

**Comment by painful-bug** [comment]
I am having the same issuewhat should I do?
