### ISSUE TITLE
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by DesTinY0x01** [wit-ai/wit#2489]
**Hello, I got this error while testing my python code (Speech API):**

Traceback (most recent call last):
  File "C:\Users\XXXXXX\Desktop\Scripts\wit.py", line 74, in <module>
    resp = client.speech(f, {'Content-Type': 'audio/wav'})
  File "C:\Users\XXXXXX\Desktop\Scripts\venv\lib\site-packages\wit\wit.py", line 89, in speech
    resp = req(self.logger, self.access_token, 'POST', '/speech', params,
  File "C:\Users\XXXXXX\Desktop\Scripts\venv\lib\site-packages\wit\wit.py", line 42, in req
    raise WitError('Wit responded with status: ' + str(rsp.status_code) +
wit.wit.WitError: Wit responded with status: 500 (Internal Server Error)

**My App ID: 472446664159139**

**Comment by brunocanti** [comment]
Have same issue : 
'Wit responded with status: 500 (Internal Server Error)',)
App ID 1404017363363052

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
