### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ldco2016** [wit-ai/wit#562]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
I am reporting a bug.

**What is the current behavior?**
I continue to get an Internal Server Error in terminal when I ask my bot questions I added as entities in wit.ai.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I wrote this get request in witClient.js:
```
'use strict';

const request = require('superagent');

function handleWitResponse(res){
  console.log(res);
}

module.exports = function witClient(bot_token) {
  const ask = function ask(message, cb) {

    request.get('https://api.wit.ai/message')
      .set('Authorization','Bearer' + bot_token)
      .query({v: '1234567'})
      .query({q: message})
      .end((err, res) => {
        if (err) return cb(err);

        if (res.statusCode != 200) return cb('Expected status 200 but got ' + res.statusCode);

        const witResponse = handleWitResponse(res.body);
        return cb(null, witResponse);
      })
  }

  return {
    ask: ask
  }
}
```
Then I wrote this in slackClient.js:
```
'use strict'

const RtmClient = require('@slack/client').RtmClient;
const CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS;
const RTM_EVENTS = require('@slack/client').RTM_EVENTS;
let rtm = null;
let nlp = null;

function handleOnAuthenticated(rtmStartData) {
  console.log(`Logged in as ${rtmStartData.self.name} of team ${rtmStartData.team.name}, but not yet connected to a channel`);
}

function handleOnMessage(message) {

  nlp.ask(message.text, (err, res) => {
    if (err) {
      console.log(err);
      return;
    }

    if (!res.intent) {
      return rtm.sendMessage("Sorry, I don't know what you are talking about.", message.channel)
    } else if (res.intent[0].value == 'time' && res.location) {
      return rtm.sendMessage(`I don't yet know the time in ${res.location[0].value}`, message.channel)
    } else {
      console.log(res);
      return rtm.sendMessage("Sorry, I don't know what you are talking about.", message.channel)
    }
    // This will send the message 'this is a test message' to the channel identified by id 'C0CHZA86Q'
    rtm.sendMessage('Sorry, I did not understand', message.channel, function messageSent() {
      // optionally, you can supply a callback to execute once the message has been sent
    });
  });

}

function addAuthenticatedHandler(rtm, handler) {
  rtm.on(CLIENT_EVENTS.RTM.AUTHENTICATED, handler);
}

module.exports.init = function slackClient(bot_token, logLevel, nlpClient){
  rtm = new RtmClient(bot_token);
  nlp = nlpClient;
  addAuthenticatedHandler(rtm, handleOnAuthenticated);
  rtm.on(RTM_EVENTS.MESSAGE, handleOnMessage)
  return rtm;
}

module.exports.addAuthenticatedHandler = addAuthenticatedHandler;

```
In terminal I run node bin/run.js and when I type How late it is in Phoenix? inside of Slack, I get this error in terminal:
```
Logged in as microurb of team urban-farming, but not yet connected to a channel
iris is listening on 3000 in development mode.
{ Error: Internal Server Error
    at Request.callback (/Users/danale/Projects/iris/node_modules/superagent/lib/node/index.js:675:11)
    at /Users/danale/Projects/iris/node_modules/superagent/lib/node/index.js:883:18
    at IncomingMessage.<anonymous> (/Users/danale/Projects/iris/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  status: 500,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"error":"Bad auth, check token\\/params","code":"no-auth"}',
```

**What is the expected behavior?**
The expected behavior is for my bot to respond with I do not yet know the time in Phoenix.

**What is the App ID where you are experiencing this issue (if applicable)?**
This is the App ID: 591a4ffd-1a1f-4067-aec9-f5ff216a6635

**Comment by l5t** [comment]
It seems like an authentication issue, are you sure about your token? Can you try with Wittyfiddle to troubleshoot? https://github.com/wit-ai/witty-fiddle

**Comment by ldco2016** [comment]
Well I took this:
curl \
 -H 'Authorization: Bearer <the-wit-token>' \
 'https://api.wit.ai/message?v=20170516&q='

And put it here into this witClient.js file:
```
'use strict';

const request = require('superagent');

function handleWitResponse(res){
  return res.entities;
}

module.exports = function witClient(bot_token) {
  const ask = function ask(message, cb) {

    request.get('https://api.wit.ai/message')
      .set('Authorization','Bearer' + bot_token)
      .query({v: '20170515'})
      .query({q: message})
      .end((err, res) => {
        if (err) return cb(err);

        if (res.statusCode != 200) return cb('Expected status 200 but got ' + res.statusCode);

        const witResponse = handleWitResponse(res.body);
        return cb(null, witResponse);
      })
  }

  return {
    ask: ask
  }
}
```

This is my run.js file:
```
'use strict'

const slackClient = require('../server/slackClient');
const service = require('../server/service');
const http = require('http');

const server = http.createServer(service);

const witToken = '<the-wit-token';
const witClient = require('../server/witClient')(witToken);

const slackToken = '<the-slack-token>';
const slackLogLevel = 'verbose';

const rtm = slackClient.init(slackToken, slackLogLevel, witClient);
rtm.start();

slackClient.addAuthenticatedHandler(rtm, () => server.listen(3000));

server.on('listening', function(){
  console.log(`iris is listening on ${server.address().port} in ${service.get('env')} mode.`);
});

```
Is the get request written wrong? is the authentication implemented wrong?

**Comment by patapizza** [comment]
It looks like you're missing a space after `Bearer`.

So instead of: `.set('Authorization','Bearer' + bot_token)`,
try: `.set('Authorization','Bearer ' + bot_token)`.
