### ISSUE TITLE
Something went wrong. We\'ve been notified.

### ISSUE THREAD

**Issue by recime-platform** [wit-ai/wit#915]
I get the following exception while creating an app using the API:

Here is the log from our server:
```
  { Error: Something went wrong. We've been notified.
      at Request.request [as _callback] (/var/task/lib/http-client.js:77:33)
      at Request.self.callback (/var/task/node_modules/request/request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/var/task/node_modules/request/request.js:1163:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1085:12)
      at IncomingMessage.g (events.js:292:16)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:185:7)
      at endReadableNT (_stream_readable.js:974:12)
      at /var/task/node_modules/async-listener/glue.js:188:31
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9) statusCode: 500 },
 context: 
  { source: 'http.request',
    params: 
     { method: 'POST',
       url: 'https://api.wit.ai/apps',
       json: true,
       gzip: true,
       headers: 
        { 'user-agent': 'recime.io/1.0',
          authorization: 'Bearer xxx' },
       qs: { v: '20170307' },
       timeout: 15000,
       body: 
        { name: 'dddad821b21ba7b8df71c872cffbb7b5',
          desc: 'A Bot',
          private: true,
          lang: 'en' } },
    result: 
     { error: 'Something went wrong. We\'ve been notified.',
       code: 'wit' },
    stat: 
     { started: 2,
       concurrent: 1,
       error: { local: 0, remote: 2 },
       success: 0,
       completed: 1 } } }

```

Regards
Mehfuz

**Comment by stopachka** [comment]
Hey Mefhuz, Are you able to repro this error repeatedly? If yes, could you email me the exact request as a CURL?
 - trying to create the app above worked, and looking in the past 10 days I was not able to find an error related to an app with that name

**Comment by recime-platform** [comment]
Hi Stefan,
It working now. I will log it extensively. It's kind of random and not sure why it is happening.

Regards
Mehfuz

**Comment by stopachka** [comment]
Cheers @recime-platform -- my hunch is that this may be related to lapses in a specific part of our old infra. If you could let me know the time window of a request (i.e error happened at this time) -- it would be very helpful. 

Looking forward to squashing this bug!
